// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgQDQmP6dfMzshNooB8l125jJQSok9J6g',
    appId: '1:945081107071:android:7941adcab874d58ab2354a',
    messagingSenderId: '945081107071',
    projectId: 'tripin-2ffc3',
    storageBucket: 'tripin-2ffc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIeTebc9FSjCzm8KzPbpzVGWKUG7VTxBA',
    appId: '1:945081107071:ios:2565bf2683af6629b2354a',
    messagingSenderId: '945081107071',
    projectId: 'tripin-2ffc3',
    storageBucket: 'tripin-2ffc3.appspot.com',
    iosClientId: '945081107071-pp0lgnr6brp2a28tna8ne8e8qsr3mbmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tripin',
  );
}
